name: gitleaks

on: [push, pull_request, workflow_dispatch]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Gitleaks
        id: gitleaks
        uses: DariuszPorowski/github-action-gitleaks@v1.0.5
        with:
          format: "sarif"
          fail: false
      - name: Get the output from the gitleaks step
        run: |
          echo "exitcode: ${{ steps.gitleaks.outputs.exitcode }}"
          echo "result: ${{ steps.gitleaks.outputs.result }}"
          echo "report: ${{ steps.gitleaks.outputs.report }}"
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.gitleaks.outputs.report }}
